# Generated by Django 3.0.6 on 2020-05-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.TextField()),
                ('month', models.TextField()),
                ('day', models.TextField()),
                ('hour', models.TextField()),
                ('PM25', models.TextField()),
                ('PM10_mask', models.TextField()),
                ('retrospective', models.TextField()),
                ('city', models.TextField()),
            ],
            options={
                'db_table': 'air_quality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyAvg',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('city', models.TextField()),
                ('PM25', models.FloatField()),
            ],
            options={
                'db_table': 'monthly_avg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airpollutionapp.Question')),
            ],
        ),
    ]
